### ISSUE TITLE
authorizer and claimMapper should be configurable in yml (base or dynamic)

### ISSUE THREAD

**Issue by shaunco** [temporalio/temporal#1134]
## Expected Behavior
The new built-in authorizers and claimMappers should be configurable via base or dynamic config

## Actual Behavior
Can only configure [JWTKeyProvider and PermissionsClaimName](https://github.com/temporalio/temporal/blob/20f01da3c95d1b708a61073dca75784fdc26cd5b/common/service/config/config.go#L510) in yml, but those are ignored since NewNoopClaimMapper is hardcoded.

## Steps to Reproduce the Problem

  1. Read the release notes for v1.5.0
  1. Read the docs at https://docs.temporal.io/docs/server-security#authorizer-plugin-interface
  1. Dig through all the configs in https://github.com/temporalio/temporal/tree/master/config
  1. Realize that [cmd/server/main.go](https://github.com/temporalio/temporal/blob/20f01da3c95d1b708a61073dca75784fdc26cd5b/cmd/server/main.go#L134) currently hardcodes NewNoopClaimMapper and that you can only enable JWKS/RSA bearer token authorization and JWT claim mapping by building your own server from code. 

## Specifications

  - Version: 1.5.0
  - Platform: ubuntu

**Comment by sergeybykov** [comment]
Our expectation is that most people would want to initialize claim mappers and authorizers via the [server options mechanism](https://docs.temporal.io/docs/server-options/) because we believe it is impossible to have a single one-size-fits-all set of plugins for every scenario. Another reason for the server options approach is that support for plugins in Go is very limited and brittle, which makes it impractical to try to define such plugins via declarative configuration (unlike in other languages).

By default, `NewNoopClaimMapper()` and `NewNopAuthorizer()` are used, so that we don't impose a related performance tax on customers that don't need authorization.

Hence, we expect customers to explicitly initialize claim mapper and authorizer in their code that references Temporal server as an upstream dependency. We have a sample that demonstrates how this can be done - https://github.com/temporalio/customization-samples/tree/master/extensibility/authorizer. One can use `NewDefaultJWTClaimMapper()` and `NewDefaultAuthorizer()` as is if it fits their scenario or as a base for a customized implementation.

Do you see a better way of achieving the same level of flexibility?

**Comment by shaunco** [comment]
While I agree that there are an infinite number of ways that people would want to map claims and do authorization, and for non-standard _(non-standard being "not provided by Temporal")_ cases where custom plugins are needed the user can do it via an upstream dependency, it seems like the provided claim mappers and authorizers  (JWT) should be usable through config. It looks like the config was already extended to have all the necessary options for `NewDefaultTokenKeyProvider()` to be used by `NewDefaultJWTClaimMapper()`, just no way to select `NewDefaultJWTClaimMapper()` in lieu of `NewNoopClaimMapper()`.

Given the prevalence and consistency of JWT, a significant number of users can use the official Temporal docker images + config, rather than building their own upstream CI/CD pipeline.

**Comment by sergeybykov** [comment]
Just checked with the team, and the consensus is that we do need to provide a way to select built-in plugins like these through config, so that they could be used with the standard docker images without the need to use server options.

We'll figure out how best to extend our config story for that and submit the change. Thanks for bringing it up.

**Comment by shaunco** [comment]
Any ETA on these being exposed? These missing settings are the only reason we build our own Temporal...

**Comment by sergeybykov** [comment]
Thanks for asking. This has been addressed in #1291, and the change will be included in the next release (1.8.0). Please let us know if you still see something missing.

I'll close this, now that #1291 has been merged.
