### ISSUE TITLE
Allow to customize Zaplogger config through server options

### ISSUE THREAD

**Issue by sp13ceg** [temporalio/temporal#1329]
**Is your feature request related to a problem? Please describe.**
Our organization expects log json to be in specific format with some additional values. Right now the zaplogger config is rigid and we cannot supply any customization.
 
**Describe the solution you'd like**
It will be great if there is an option to customize Zaplogger through server options. 

https://github.com/temporalio/temporal/blob/master/temporal/server.go#L107

**Comment by sp13ceg** [comment]
Hi, If this requirement make sense we can contribute to it. Thanks.

**Comment by alexshtin** [comment]
I added new server option `temporal.WithLogger()` which accepts instance of `log.Logger` interface which is:
```go
	Logger interface {
		Debug(msg string, tags ...tag.Tag)
		Info(msg string, tags ...tag.Tag)
		Warn(msg string, tags ...tag.Tag)
		Error(msg string, tags ...tag.Tag)
		Fatal(msg string, tags ...tag.Tag)
	}
```
where `tag.Tag` is another interface:
```go
	Tag interface {
		Key() string
		Value() interface{}
	}
```
This is how you can provide custom version of `zap.Logger`:
```go
	logger := log.NewZapLogger(buildMyCustomZapLogger())
	s := temporal.NewServer(
		...
		temporal.WithLogger(logger),
	)
```

Or you can completely reimplement `log.Logger` interface and use your favourite logger under the hood. `tag.Tag` can be implemented by any custom struct but if you gonna use `zap.Logger` underneath, I would recommend build tags using `tag.NewZapTag()` func.

There are also 2 axillary interfaces:
```go
	WithLogger interface {
		With(tags ...tag.Tag) Logger
	}
	SkipLogger interface {
		Skip(extraSkip int) Logger
	}

```
You can implement `WithLogger` interface with `With` method which should return new instance of your logger with prepended tags. Otherwise internal (not very efficient) preppender is used.

If your logger also implements `SkipLogger` then `Skip` method will be called and `extraSkip` parameter will have number of extra stack trace frames to skip (useful if you want to log caller func file/line).

**Comment by sp13ceg** [comment]
Thank you. I will try this.
