### ISSUE TITLE
add an option to "tctl batch start" to operate at the workflow_id level

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#1578]
Currently, the tctl batch command does a ScanWorkflowExecutions with the given query and always performs the designated operation on a workflow_id/run_id pair.

There should be an option to operate on the workflow_id level, leaving out the run_id. This, for example, would provide a more systematic way to do a guaranteed cancellation of a cron workflow (assuming the cron workflow could be identified by workflow_type)

**Comment by sunny-b** [comment]
I've been looking at this issue and I'd be up for working on it, though I have a couple of clarifying questions:

It looks like you can already use the `WorkflowId` as a [search attribute](https://docs.temporal.io/docs/concepts/what-is-a-search-attribute/) in the `query` flag. In that case, is this really needed? Or would it be just a convenience flag that would take the place of query, similar to the `workflow_id` and `workflow_type` flags for [`workflow list` command](https://github.com/temporalio/temporal/blob/master/tools/cli/workflowCommands.go#L1283-L1290)?

Additionally, it looks like adding this `workflow_id` flag would also require making sure that info gets passed through the various API calls, including `CountWorkflow` and `ExecuteWorkflow`. `ExecuteWorkflow` has a `SearchAttributes` field where you could add the `WorkflowId`, but this would need to be added to `CountWorkflow` since it only has a `query` field.

One hack that wouldn't require changes to the backend APIs is if the `workflow_id` flag is present, to generate a query from it.

Ex. `batch start --workflow_id test_workflow_id` would translate to a query like `WorkflowId='default.test_workflow_id'`

Does that seem reasonable?

**Comment by yiminc** [comment]
There is currently no plan to work on this. 
The BatchOperation APIs are implemented in a simple way that it queries visibility to fetch list of workflow executions and then apply operation on each of them. The challenge is the workflow state could change while that batch operation is running, and a cron workflow may have completed and started a new run. So if you try to batch terminate running cron workflows, your visibility query may return list of them, but by the time the batch operation get to it, it may have already completed and scheduled next run which is not in the visibility query result obtained earlier. 
A simple work around would be to run the visibility query after the batch operation and run the batch again if there are more running cron workflows.
