### ISSUE TITLE
reducing namespace retention period should delete retained workflows that exceed the new period

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#1598]
If I start out with a large retention period, realize it is too big, and then reduce it, only new Workflows will be created with the smaller retention period. We still have to wait the original retention period in order for those older workflows to get cleaned up. Would be nice if reducing the retention period gives the option of cleaning up completed workflows whose age exceeds the period.

**Comment by yiminc** [comment]
This is now possible to do via batch operation. We decided to not auto trigger a batch delete but user has the ability to trigger a batch delete with query filter for workflows that has closed for more than X days.

**Comment by gabrielalmeida** [comment]
A warning indicating the retention change will affect only new workflows would have helped a lot understanding our recent situation. A note stating that batch-delete is the way to go to handle previous retention policy leftovers would also be nice.

We had `history_nodes` table growing unexpectedly for a few days because another collaborator, unaware of this behavior, increased and then after a while reduced the retention policy. There was no easy way to track why this happened, since the current value reported by `temporal operator namespace describe` was "as expected", nor we could find any docs about this behavior.

Adding some keywords here to index them and help if someone else is struggling to find this info: `historyScannerVerifyRetention`, `historyScannerEnabled`, `WorkflowExecutionRetentionTtl`, scavenger, cleanup
