### ISSUE TITLE
Eagerly error/return on queries for workflows waiting to start

### ISSUE THREAD

**Issue by cretz** [temporalio/temporal#2300]
**Is your feature request related to a problem? Please describe.**

Queries for workflows that are scheduled but not started are causing an issue in the Go SDK (see https://github.com/temporalio/sdk-go/issues/475). This is because the SDK expects the workflow to be started before handling queries. This can happen on workflow retry, cron, and I believe also on continue-as-new.

**Describe the solution you'd like**

@mfateev suggests the server return an error in this case that the SDK will propagate to the user. One approach would be to have `temporal.api.enums.v1.QueryResultType` have a new `QUERY_RESULT_TYPE_AWAITING_EXECUTION` enum and the SDK can return a typed error in these cases.

**Describe alternatives you've considered**

We could fail on the worker side in each SDK, but there is no benefit.

Another possible alternative is to run the query on the last run workflow for that ID since the new one hasn't started yet, but I suspect that gets messy.

**Comment by yiminc** [comment]
dup of https://github.com/temporalio/temporal/issues/1310

**Comment by Spikhalskiy** [comment]
Please note that the same problem will happen if the workflow did actually start, but the first workflow task failed or timed out. If

**Comment by Spikhalskiy** [comment]
Please note that the same problem will happen if the workflow did actually start, but the first workflow task failed or timed out. SDK can't execute a direct query correctly in this case because the event loop can't be triggered and queries registration is performed in the event loop with static queries getting registered on the first triggering of this event loop.
This is true at least for JavaSDK.

We can implement a workaround with the registration of static queues ahead of time, so they will be able to answer for workflows with 0 completed workflow tasks. Dynamic queries that are registered inside the workflow method will not answer in this situation.

**Comment by Spikhalskiy** [comment]
Closed by #2826?
