### ISSUE TITLE
Fresh install and workflow results in ListClosedWorkflowExecutions, Elasticsearch error persists

### ISSUE THREAD

**Issue by nshazly** [temporalio/temporal#2671]
## Expected Behavior
Previous issue described here, suggested steps show the Elasticsearch index and schema were created and the issue persists, https://github.com/temporalio/temporal/issues/2649

Running `tctl workflow list` should respond with a list of running works flows or an empty list. Not an error.

## Actual Behavior

```
$ tctl workflow list                                                       
Error: Failed to list closed workflow.
Error Details: context deadline exceeded
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```
And the web interface shows the following error:

![image](https://user-images.githubusercontent.com/1079547/160196915-1dd3f65e-a214-4e30-8f06-a551f23c216b.png)

Additionally, 
```
$ tctl wf start --tq fake.queue --wt fake.workflow
Started Workflow Id: bf730e6e-5f21-476f-a0ae-7b2e39707326, run Id: 00356ebe-2a10-4034-844e-735cfa2f2b16

$   tctl wf term -w bf730e6e-5f21-476f-a0ae-7b2e39707326     
Error: Terminate workflow failed.
Error Details: sql: no rows in result set
```

## Steps to Reproduce the Problem

  1. Fresh install of temporal IO using elasticsearch/postgresql, version 1.15.2
  2. Run the auto-setup indexes (https://github.com/temporalio/docker-builds/blob/main/docker/auto-setup.sh#L268-L276)
  ```
$ curl -X PUT "${INDEX_URL}" --write-out "\n"
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [temporal_visibility/KbYZaZBjTuucfbR0z8si4g] 
already exists","index_uuid":"KbYZaZBjTuucfbR0z8si4g","index":"temporal_visibility"}],"type":"resource_already_exists_exception","reason":"index [temporal_visibility/KbYZaZBjTuucfbR0z8si4g] already exists","index_uuid":"KbYZaZBjTuucfbR0z8si4g","index":"temporal_visibility"},"status":400}
```
  4. Run the command `tctl n re default` to create a namespace
  5. Start a workflow `tctl wf start --tq fake.queue --wt fake.workflow --et 10`
  6. Run `tctl workflow list`
OR
   Log into the WEB Interface

## Specifications

  - Version: 1.15.2
  - Platform: K8s

$   tctl wf term -w bf730e6e-5f21-476f-a0ae-7b2e39707326     
Error: Terminate workflow failed.
Error Details: sql: no rows in result set

**Comment by alexshtin** [comment]
Elasticsearch creates indexes on demand using index template. Index name should match one of `index_patterns` specified [here](https://github.com/temporalio/temporal/blob/master/schema/elasticsearch/visibility/versioned/v1/index_template_v7.json#L4).

You index name doesn't match it and therefore it was created without applying proper template. In this case Elasticsearch created it using default "best guess" schema. In this schema `RunId` is of type `Text` (instead of `Keyword`) and it can't be used for sorting. This is what error message says. 

You need to upload modified index schema template (which will match your index name) or change your index name to match the pattern. Then delete existing index and it will be recreated by Elasticsearch automatically or you can do it with `curl` command.
