### ISSUE TITLE
Can't call multi  goroutine ExecuteActivity, ExecuteChildWorkflow  inside WorkFlow

### ISSUE THREAD

**Issue by lucy9x** [temporalio/temporal#3071]
When calling multi-goroutine ExecuteActivity inside WorkFlow the program throws an exception `panic: getState: illegal access from outside of workflow context`. 
To understand let's see my example. I can't call multi goroutine `TestActivity`  in `TestWorkFlow`,  an exception throw: `panic: getState: illegal access from outside of workflow context`. This is the same when calling multi goroutine ExecuteChildWorkflow inside WorkFlow

```go
func TestWorkFlow(ctx workflow.Context) (bool, error) {
	ao := workflow.ActivityOptions{
		StartToCloseTimeout: 24 * time.Hour,
	}
	ctx = workflow.WithActivityOptions(ctx, ao)
	gologger.Info().Msg("start test workflow")
	var wg sync.WaitGroup
	for i := 0; i < 5; i++ {
		wg.Add(1)
		future := workflow.ExecuteActivity(ctx, TestActivity, i+1)
		go func(future workflow.Future) {
			defer wg.Done()
			var done bool
			future.Get(ctx, &done)
		}(future)
		time.Sleep(time.Second)
	}
	wg.Wait()
	gologger.Info().Msg("complete test workflow")
	return true, nil
}

func TestActivity(ctx context.Context, index int) (bool, error) {
	gologger.Info().Msgf("start activity test %d", index)
	time.Sleep(5 * time.Second)
	gologger.Info().Msgf("complete activity test %d", index)
	return true, nil
}
```

My question is how to call multi goroutine `ExecuteActivity`  or `ExecuteChildWorkflow` insite a Workflow
## Specifications

  - Version: latest
  - Platform: windows 10

**Comment by yycptt** [comment]
Workflow code must be deterministic, so `go` can't be used inside workflow definition. Please use the [`workflow.Go`](https://pkg.go.dev/go.temporal.io/sdk@v1.15.0/workflow#Go) instead.

`time.Sleep` also should not be used. Use `[workflow.Sleep](https://pkg.go.dev/go.temporal.io/sdk@v1.15.0/workflow#Sleep)` instead.

You don't have to use `workflow.Go` in order to run activities in parallel. As long as the first activity future.Get call is after all `workflow.ExecuteActivity`, those activities will run in parallel. 

So all that's needed is a for loop to execute all activities and then another for loop to call Get on the futures.

**Comment by lucy9x** [comment]
> Workflow code must be deterministic, so `go` can't be used inside workflow definition. Please use the [`workflow.Go`](https://pkg.go.dev/go.temporal.io/sdk@v1.15.0/workflow#Go) instead.
> 
> `time.Sleep` also should not be used. Use [`workflow.Sleep`](https://pkg.go.dev/go.temporal.io/sdk@v1.15.0/workflow#Sleep) instead.
> 
> You don't have to use `workflow.Go` in order to run activities in parallel. As long as the first activity future.Get call is after all `workflow.ExecuteActivity`, those activities will run in parallel.
> 
> So all that's needed is a for loop to execute all activities and then another for loop to call Get on the futures.

Thank @yycptt for your response. 

After modifying my code according to your instructions, my code worked as expected
