### ISSUE TITLE
Support ElasticSearch 7

### ISSUE THREAD

**Issue by markmark206** [temporalio/temporal#313]
The current codebase expects elastic search 6 (we currently test with 6.8.8)

Please add support for ElasticSearch 7 (as of this writing, the current version is 7.6.2).

**Comment by kgignatyev** [comment]
Please upgrade to 7 ASAP, because it causes problems with custom search attributes - they make it to ES, but because mapping does not include them, search does not work. For example search {
  "query": {
         "term": { 
					 "Attr.lenderID": "lender-1"
				 }       
  }
}


does not work until mappings is not updated
![image](https://user-images.githubusercontent.com/868783/97834219-219f0180-1c8c-11eb-8142-ed889b6a1b5d.png)

**Comment by alexshtin** [comment]
Added in #1164.
