### ISSUE TITLE
Consider increasing default for frontend.visibilityListMaxQPS

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#322]
A lot of users are running into 

`8 RESOURCE_EXHAUSTED: Persistence Max QPS Reached for List Operations. `

The current default was reasonable for internal Uber use, but not for the open source version.

**Comment by sunjiawen** [comment]
Steven Sun  18 minutes ago
@maxim I think something is wrong, because I have the same settings for cadence UI and server and much more workflows and never see this problem, but I might be wrong (edited) 

Shanan Sussman  3 minutes ago
For what its worth, i've encountered this when running Temporal locally with only 1 namespace & tasklist with <5 executions. Every time i've seen it after doing a browser refresh on the page

**Comment by wxing1292** [comment]
issue no longer relevant
