### ISSUE TITLE
Cancel event has been leak because of concurrent reason, when the workflow return ContinueAsNew

### ISSUE THREAD

**Issue by qiuyuzhou** [temporalio/temporal#3241]
The `WorkflowExecutionCancelRequested` event from parent workflow has not been processed.

![image](https://user-images.githubusercontent.com/2310221/185049067-26f64b19-2040-4f87-b71f-997e15c10ac0.png)

[76fc37e5-78fa-4de4-9bda-07b88bd71e81_events.json.zip](https://github.com/temporalio/temporal/files/9356928/76fc37e5-78fa-4de4-9bda-07b88bd71e81_events.json.zip)

```go
		err1 := workflow.Sleep(ctx, conf.LoopInterval)
		if err1 != nil {
			return
		}

		err = workflow.NewContinueAsNewError(ctx, WorkflowOrderDispatchProduct.Name(), w.request)
```

## Steps to Reproduce the Problem

Because it is cause by concurrent reason,  it's hard to reproduce it.

## Specifications

Temporal: v1.7.2
Go SDK: v1.15.0

**Comment by yiminc** [comment]
When a workflow received a cancellation request, its workflow.Context will be cancelled, but it is up to the workflow's code to decide what to do with that cancellation. The workflow can decide to honor the cancellation request by return a CancelledError, or it can ignore that request and do something else. In your case, it seems the workflow decided to do a continue as new. This is expected behavior.
