### ISSUE TITLE
SignalWithStart and cron

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#3805]
SignalWithStart called after wf execution is created causes server to schedule workflow task right away. 
This causes issues with cron executions because scheduling this workflow task disregards firstWorkflowTaskBackoff timer.

Fix would be to not ignore this firstWorkflowTaskBackoff. Thanks.

**Comment by dnr** [comment]
On the other hand, this is a slightly-sneaky way to do "run immediately" with the old cron feature, and I wouldn't be surprised if people were depending on the current behavior. This is unlikely to be "fixed".

**Comment by tsurdilo** [comment]
Yeah thats a good thing to know I guess but not sure if users even know about this feature thats not documented to be using it to bypass their cron definition. So do you think this is not a concern with schedules?

**Comment by Albert-Coding** [comment]
fwiw, this feels like a bug because the behaviour is unexpected and different depending on if a workflow with the ID is already running.

Also, what is the implied new cron feature?

**Comment by dnr** [comment]
It's definitely a bug, but it's in an old feature that no one is actively working on. And as I said, I'd be worried about the fix breaking someone who happened to be depending on it (maybe accidentally). It would be fair but still potentially disruptive.

The new feature is https://docs.temporal.io/workflows#schedule

Schedules don't support SignalWithStart (or Signal) yet, only Start. But this wouldn't be a problem because it works totally differently and doesn't use FirstWorkflowTaskBackoff.
