### ISSUE TITLE
Add ActivityType to MutableState

### ISSUE THREAD

**Issue by yycptt** [temporalio/temporal#4537]
**Is your feature request related to a problem? Please describe.**
- Currently to know the activityType, we need to read workflow history and find the type in the activity scheduled events.
- For DescribeWorkflowExecution, we need to load activity scheduled event for each pending activity which can be quite expensive as there can be at most 2k pending activities.

**Describe the solution you'd like**
- Add ActivityType to MutableState's ActivityInfo
- https://github.com/temporalio/temporal/blob/master/service/history/api/describeworkflow/api.go#L145
- Do not read history event if activityType is available in activityInfo

**Describe alternatives you've considered**

**Additional context**

**Comment by yycptt** [comment]
Not sure if I follow the question. But I don't think activity type can change once scheduled.

**Comment by paulnpdev** [comment]
I think he's asking if we could add a field "mostRecentActivityType" to the MS (and populate it every time we process a completed activity) so that we don't have to go load history to find out what it was when processing the next UpdateWorkflow.  I believe there are cases where you need to know what the previous ActivityType was.  

this is all a guess :)

**Comment by rodrigozhou** [comment]
@paulnpdev The mutable state contains a list of pending activities. The task here is to add the activity type to each pending activity object in mutable state.
