### ISSUE TITLE
Visibility Archival On, History Archival Off for a namespace causes panic

### ISSUE THREAD

**Issue by tristan-instacart** [temporalio/temporal#4879]
## Expected Behavior
No panic

## Actual Behavior
Panic in history service

## Steps to Reproduce the Problem

  1. have a namespace called NAMESPACE_NAME with archival on for both visibility and history and have it make workflows that close past its retention period, i.e. it should be archiving stuff
  1. Run $ tctl --ns NAMESPACE_NAME namespace update --history_archival_state disabled
  1. Watch the history service panic and never survive ever again as the workflow will continuously retry to archive and die.

## Specifications

  - Version: 1.20.4 (confirmed code is still got the bug in 1.22)
  - Platform: linux docker

The bug is here:
Here is the nil value de-reference: https://github.com/temporalio/temporal/blob/f64bb0eb0f474d03775673b68a341393b48e9891/service/history/archival/archiver.go#L263

Here is how it gets init to nil and never set to a value:
https://github.com/temporalio/temporal/blob/008f056d6528142929b30aeea7a0648c2c0fef16/service/history/archival_queue_task_executor.go#L162-L201

**Comment by ytaben** [comment]
Would a proper fix be to make `archiver.uri.String` method return an empty string instead of a panic?

Our understanding is that for all intents and purposes - the `HistoryURI` is not set for the visibility archival record so it should just be empty. We can fix it either in this specific place or as in the suggestion above - for any uri instance.

CC @yycptt and @MichaelSnowden as you are the respective authors for the code in question

**Comment by ytaben** [comment]
Note: Since we are not actually setting the HistoryURI to nil (it's an empty interface) - we can't fix this by handling `nil` receiver alone.

I've made a targeted fix [here](https://github.com/temporalio/temporal/pull/4880) instead
