### ISSUE TITLE
image tags in dockerhub now start with "v"?

### ISSUE THREAD

**Issue by bllfr0g** [temporalio/temporal#5112]
The docker images for 1.22.2 just hit dockerhub and its tag is “v1.22.2”.

For previous versions, the tag was 1.22.1, 1.22, etc.

Was this change intentional?

Incidentally, there are now tags “1.22” and “v1.22” that point to different images, so I am guessing that was not intentional?

**Comment by MikeFear** [comment]
Please **stop** removing already published Docker image tags from Dockerhub. We use Renovatebot which automatically fetches new image tags and updates the references in our project. This broke our e2e test setup because the Docker image which was green and available before suddenly disappeared. This is at least the second time this happened in the recent weeks.

Docker image tags should only be removed under critical circumstances if there is a serious bug in the release or security flaw not just because there was a mistake in the naming. It doesn't matter if multiple tags point to the same image.

**Comment by rodrigozhou** [comment]
Correct tags have been published already.
Sorry about causing issues @MikeFear, we will be more careful and try to avoid deleting tags.
