### ISSUE TITLE
CLI unable to show describe workflow output when it has heartbeat data

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#516]
## Expected Behavior
describe output should show workflow details.

## Actual Behavior
```
tctl --ns benchtest wf desc -w 1
Error: Unable to decode heartbeat details.
Error Details: payload item 0: unable to decode JSON: json: cannot unmarshal number into Go value of type string
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```

## Steps to Reproduce the Problem

  1.  Run a workflow which runs long running activity
  1.  Activity heartbeats with some details
  1.  Run tctl to dump workflow details
```
tctl --ns benchtest wf desc -w 1
```

## Specifications

  - Version:  0.26.0
  - Platform:

**Comment by mastermanu** [comment]
Looks like the CLI is completely broken when it comes to interpreting the server response.

The server response returns *commonpb.Payloads which basically contains an array of *Payload structs. Each payload struct indicates whether it is a raw byte array of a json marshalled object.

In this case, we are returning from the server:

Payloads{
   Payloads: []Payload{
       Metadata: {{"encoding":"json:}},
       Data: <byte array of an int32 that has been marshalled to JSON>
   }
}

We are then unmarshalling the JSON number and then trying to assign it to a string pointer. You can't assign a number to an integer, which is the error you are getting.

So there are two bugs here:
1) For the purposes of the CLI, rather than trying to unmarshall the JSON value, we should maybe consider just returning the raw JSON byte array converted to a string

2) The code as it is doesn't handle the case where MULTIPLE arguments are passed to activity.RecordHeartbeat(). It will only ever surface the first one.

It also looks like temporal-web is broken as well:
It returns the metadata.encoding as json, the metadata.encoding_base64 as anNvbg== (which is just the base64 version of "json", which is rather pointless) and then the actual data field (which is the most useful portion) is blank. Will open a separate issue on this one tomorrow.

**Comment by mastermanu** [comment]
This has been fixed here: https://github.com/temporalio/temporal/pull/525
