### ISSUE TITLE
Ability to clear/unset search attributes

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#561]
**Is your feature request related to a problem? Please describe.**
As of right now, Search Attributes can only be set and updated but not cleared. In order to simulate a clear we can set the value to some sentinel value, e.g Int being set to -1.

**Describe the solution you'd like**
Documents would stay cleaner and queries more simplified if these search attributes could just be “unset”.

**Describe alternatives you've considered**
Set key to a sentinel value.

**Additional context**
[forum post](https://community.temporal.io/t/ability-to-clear-unset-search-attributes/211)

**Comment by alexshtin** [comment]
Another option would be to add some flag to `Payload` metadata indicating that this search attribute needs to be deleted on server.

**Comment by Spikhalskiy** [comment]
I temporarily work around this issue in java-sdk by sending an empty collection, because it will work correctly.
I also encourage to consider `[]` (empty list) as a magic value in the upsert that deletes the search attribute. 
Search attributes do already support lists. Having a search attribute with a persisted empty collection value doesn't make sense, because it does nothing. And this value is semantically close to removing and looks organic, universal for all types, non-conflicting with anything meaningful and not made up.

**Comment by alexshtin** [comment]
Both `nil` and empty slice values clears search attributes now.
