### ISSUE TITLE
DynamoDB persistence driver

### ISSUE THREAD

**Issue by jvassev** [temporalio/temporal#684]
Have you considered adding a DynamoDB persistence option. From what I can see it would be very close to the Cassandra driver.

I could work on that feature with some guidance.

One thing that I am not sure how to map to Dynamo are shards: ` An adapter to any other database that provides multi-row single shard transactions can be added.`. DynamoDB transactions are limited just by [size](https://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/transaction-apis.html). Given this constraint, isn't it better to have just one shard?
An alternative design would be one table per shard - but such a design would be hard to manage/scale, more expensive and unusual?

What do you think about this?

**Comment by samarabbas** [comment]
Considering the size limitations for DynamoDB transactions it won't be a feasible option as persistence store for Temporal.

**Comment by roded** [comment]
Has anything change with regards to this question? Is the answer the same and not expected to change?
TY

**Comment by swordfish444** [comment]
@samarabbas @sunfmin Support for DynamoDB would be a *huge unlock* for enterprise companies (running on AWS), looking to use Temporal at scale. 

Can we re-open this issue and do a deeper investigation into how this may be achieved? Even if an initial solution was more of a "hybrid" solution, where the write-heavy models leverage DynamoDB.

**Comment by JobaDiniz** [comment]
I was wondering the same and then I got here in the *closed* issue :(.

*Truly* scaling Postgres is hard compared to how DynamoDB scales.

>Considering the size limitations for DynamoDB transactions it won't be a feasible option as persistence store for Temporal.

When using DynamoDB, you should _avoid_ transactions. They are not typical SQL transactions. You usually design the table in a way to avoid needing transactions, because most of the time, they are *not needed* in DynamoDB.

DynamoDB is [schemaless](https://aws.amazon.com/blogs/database/should-your-dynamodb-table-be-normalized-or-denormalized/), very different from any other supported temporal databases.

We would need to understand [access patterns](https://docs.aws.amazon.com/prescriptive-guidance/latest/dynamodb-data-modeling/step3.html) **before** designing the `items` and `item collection` in DynamoDB. I think it's possible to integrate with DynamoDB, but it won't be easy since temporal relies on SQL normalized architecture - *said by me, who do not understand Temporal innards*. 

I could work with someone as well to create a PoC for this. [Postgres schema](https://github.com/temporalio/temporal/blob/main/schema/postgresql/v12/temporal/schema.sql).
