### ISSUE TITLE
Temporal Web UI still show completed workflow as running

### ISSUE THREAD

**Issue by sunjiawen** [temporalio/temporal#888]
Temporal Web UI still show completed workflow as running
![Screen Shot 2020-10-22 at 9 38 42 AM](https://user-images.githubusercontent.com/1476377/96903781-1efe0a00-144b-11eb-94ec-9c44c894f02c.png)
![Screen Shot 2020-10-22 at 9 38 28 AM](https://user-images.githubusercontent.com/1476377/96903872-3a691500-144b-11eb-9df5-a45b09902c5b.png)

**Comment by feedmeapples** [comment]
steps to repro:
1. Elastic Search should be disabled
2. Run a considerable load of workflows (ex. 25k+)
3. Wait until the workflows finish
4. Open workflows list page on Web UI (or just execute openWorkflows request)

expected:
- Workflows shouldn't be part of Open workflows response
actual:
- Open workflows request still returns completed workflows

Note:
When the cluster is overloaded visibility records may be dropped. This is planned to be fixed with Kafka removal effort

**Comment by samarabbas** [comment]
This is expected behavior.  Visibility API provides eventually consistent semantics, so in the case of certain failure conditions like backlog on visibility queue a closed workflow might appear in the list of open workflow executions until system is able to churn through the entire backlog.  
On the other hand summary page uses DescribeWorkflow execution api which is strongly consistent.
